import { NextResponse } from 'next/server';
import crypto from 'crypto';

// ---------------------------------------------------------------------------
// Production Configuration & Validation
// ---------------------------------------------------------------------------
// Fail fast at boot time if required environment variables are missing.
// ---------------------------------------------------------------------------
const DOWNLOAD_SECRET = process.env.DOWNLOAD_SECRET;
const SECURE_DOWNLOAD_URL = process.env.SECURE_DOWNLOAD_URL;

if (!DOWNLOAD_SECRET) {
  throw new Error(
    'FATAL: DOWNLOAD_SECRET is not defined. Set a strong random string in .env.local'
  );
}

// ---------------------------------------------------------------------------
// GET /api/download?token=<base64url-token>
// ---------------------------------------------------------------------------
// Validates the temporary secure token generated by /api/activate.
// If the token is valid and not expired, the user is redirected to the
// final secure file location (e.g., a pre-signed S3 URL or CDN link).
// ---------------------------------------------------------------------------
export async function GET(request) {
  try {
    // 1. Extract the token from the query string.
    const { searchParams } = new URL(request.url);
    const token = searchParams.get('token');

    if (!token) {
      return NextResponse.json(
        { error: 'Missing download token.' },
        { status: 400 }
      );
    }

    // 2. Decode the base64url token back into payload + signature.
    const decoded = Buffer.from(token, 'base64url').toString('utf-8');
    const [payload, signature] = decoded.split('.');

    if (!payload || !signature) {
      return NextResponse.json(
        { error: 'Invalid token format.' },
        { status: 400 }
      );
    }

    // 3. Recompute the HMAC signature to verify token integrity.
    const expectedSignature = crypto
      .createHmac('sha256', DOWNLOAD_SECRET)
      .update(payload)
      .digest('hex');

    if (signature !== expectedSignature) {
      return NextResponse.json(
        { error: 'Invalid download token.' },
        { status: 403 }
      );
    }

    // 4. Parse the JSON payload and check the expiration timestamp.
    const { exp, licenseKey } = JSON.parse(payload);

    if (Date.now() > exp) {
      return NextResponse.json(
        { error: 'Download link has expired.' },
        { status: 403 }
      );
    }

    // 5. Ensure the backend file target is configured.
    if (!SECURE_DOWNLOAD_URL) {
      return NextResponse.json(
        { error: 'Download URL not configured on the server.' },
        { status: 500 }
      );
    }

    // 6. Redirect the user to the actual secure file.
    //    In production, you might instead proxy the file stream so the
    //    origin URL is never exposed in the browser's network tab.
    return NextResponse.redirect(SECURE_DOWNLOAD_URL);
  } catch (err) {
    // 7. Handle malformed tokens or unexpected failures gracefully.
    console.error('Download error:', err);
    return NextResponse.json(
      { error: 'Invalid download token.' },
      { status: 400 }
    );
  }
}
